### ISSUE TITLE
weird result of new-session with no flags how do I remove it from sessions?

### ISSUE THREAD

**Issue by Asternitix** [kbsecret/kbsecret.github.io#2]
/var/lib/gems/2.3.0/gems/kbsecret-0.9.2/lib/kbsecret/config.rb:143:in `block (2 levels) in <class:Config>': Unknown session: '' (KBSecret::Exceptions::SessionUnknownError)
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.2/lib/kbsecret/cli/kbsecret-sessions:20:in `block in <main>'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.2/lib/kbsecret/cli/kbsecret-sessions:19:in `each'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.2/lib/kbsecret/cli/kbsecret-sessions:19:in `<main>'

**Comment by woodruffw** [comment]
Could you elaborate a little further? You created a session with no flags and an empty string?

**Comment by woodruffw** [comment]
If I understand correctly, this was fixed in https://github.com/kbsecret/kbsecret/commit/c8cc0d1daabb68bda630803fefe7fc7c73341065.

I haven't pushed a new version for it yet, but it'll be in `0.9.3`. In the meantime, providing the contents of your config file (`~/.config/kbsecret/config.yml`) with any parts you consider sensitive removed would help me figure out how to fix your local state 😄

**Comment by Asternitix** [comment]
# frozen_string_literal: true

require "fileutils"
require "inih"
require "shellwords"
require "yaml"

module KBSecret
  # Global and per-session configuration for kbsecret.
  class Config
    # The configuration directory.
    # @api private
    CONFIG_DIR = File.expand_path("~/.config/kbsecret").freeze

    # The configuration file.
    # @api private
    CONFIG_FILE = File.join(CONFIG_DIR, "config.yml").freeze

    # The command configuration file.
    # @api private
    COMMAND_CONFIG_FILE = File.join(CONFIG_DIR, "commands.ini").freeze

    # The directory searched for custom record types.
    # @api private
    CUSTOM_TYPES_DIR = File.join(CONFIG_DIR, "record").freeze

    # Configuration facets used for method generation.
    # @api private
    CONFIG_FACETS = {
      session: {
        plural: :sessions,
        except: Exceptions::SessionUnknownError,
      },

      generator: {
        plural: :generators,
        except: Exceptions::GeneratorUnknownError,
      },
    }.freeze

    # The default session configuration.
    DEFAULT_SESSION = {
      default: {
        users: [Keybase::Local.current_user],
        root: "default",
      },
    }.freeze

    # The default generator configuration.
    DEFAULT_GENERATOR = {
      default: {
        format: "hex",
        length: 16,
      },
    }.freeze

    # configuration defaults
    # @api private
    DEFAULT_CONFIG = {
      mount: "/keybase",
      sessions: DEFAULT_SESSION.dup,
      generators: DEFAULT_GENERATOR.dup,
    }.freeze

    # Writes the user's configuration to disk.
    # @return [void]
    def self.sync!
      File.open(CONFIG_FILE, "w") { |io| io.write @config.to_yaml }
    end

    # Retrieve a configured value.
    # @param key [String] the configuration key to retrieve
    # @return [Object] the corresponding configuration
    def self.[](key)
      @config[key]
    end

    # Fetch the configuration for a `kbsecret` command.
    # @param cmd [String] the short name of the command
    # @return [Hash, nil] the command's configuration
    # @example
    #  # retrieves the config for `kbsecret-list`
    #  Config.command("list") # => { "args" => "...",  }
    def self.command(cmd)
      @command_config[cmd]
    end

    # Fetch the configured default arguments for a `kbsecret` command.
    # @param cmd [String] the short name of the command
    # @return [Array] the command's default arguments
    # @note Default arguments are split according to normal shell splitting rules.
    # @example
    #  Config.command_args("list") # => ["--show-all"]
    def self.command_args(cmd)
      @command_config.dig(cmd, "args")&.shellsplit || []
    end

    # @!method session(label)
    #   Retrieve a session's configuration.
    #   @param label [String, Symbol] the session's label
    #   @return [Hash] the session configuration
    #   @raise [Exceptions::SessionUnknownError] if no such session exists
    # @!method session_labels
    #   @return [Array<Symbol>] all configured session labels
    # @!method session?(label)
    #   @param label [String, Symbol] the session label
    #   @return [Boolean] whether or not the given session is configured
    # @!method configure_session(label, hsh)
    #   Configure a session.
    #   @param label [String, Symbol] the session label
    #   @param hsh [Hash] the session configuration
    #   @return [void]
    # @!method deconfigure_session(label)
    #   Deconfigure a session.
    #   @param label [String, Symbol] the session label
    #   @return [void]
    #   @note This only removes the given session from the configuration, making
    #    it "invisible" to `kbsecret`. To actually remove all files associated
    #    with a session, see {KBSecret::Session#unlink!}.
    # @!method generator(label)
    #   Retrieve a generator's configuration.
    #   @param label [String, Symbol] the generator's label
    #   @return [Hash] the generator configuration
    #   @raise [Exceptions::GeneratorUnknownError] if no such generator exists
    # @!method generator_labels
    #   @return [Array<Symbol>] all configured session labels
    # @!method generator?(label)
    #   @param label [String, Symbol] the generator label
    #   @return [Boolean] whether or not the given generator is configured
    # @!method configure_generator(label, hsh)
    #   Configure a secret generator.
    #   @param label [String, Symbol] the generator label (profile name)
    #   @param hsh [Hash] the generator configuration
    #   @return [void]
    # @!method deconfigure_generator(label)
    #   Deconfigure a generator.
    #   @param label [String, Symbol] the generator label (profile name)
    #   @return [void]
    CONFIG_FACETS.each do |facet, data|
      define_singleton_method facet do |label|
        hsh = @config[data[:plural]][label.to_sym]

        raise data[:except], label unless hsh

        hsh
      end

      define_singleton_method "#{facet}_labels" do
        @config[data[:plural]].keys
      end

      define_singleton_method "#{facet}?" do |label|
        @config[data[:plural]].keys.include? label.to_s
      end

      define_singleton_method "configure_#{facet}" do |label, **hsh|
        @config[data[:plural]][label.to_s] = hsh
        sync!
      end

      define_singleton_method "deconfigure_#{facet}" do |label|
        @config[data[:plural]].delete(label.to_s)
        sync!
      end
    end

    user_config = if File.exist?(CONFIG_FILE)
                    YAML.load_file(CONFIG_FILE)
                  else
                    FileUtils.mkdir_p CONFIG_DIR
                    DEFAULT_CONFIG
                  end

    @command_config = if File.exist?(COMMAND_CONFIG_FILE)
                        INIH.load(COMMAND_CONFIG_FILE)
                      else
                        {}
                      end

    @config = DEFAULT_CONFIG.merge(user_config)
    @config[:sessions].merge!(DEFAULT_SESSION)
    @config[:generators].merge!(DEFAULT_GENERATOR)

    sync!
  end
end
this is the config file.

**Comment by woodruffw** [comment]
That's `config.rb`, not the config file. The config file is `~/.config/kbsecret/config.yml`.

**Comment by Asternitix** [comment]
well, that explains the many error messages when I made changes to it.

**Comment by Asternitix** [comment]
I haven't made any changes to config.yml so it should be normal.

**Comment by woodruffw** [comment]
Okay. Try updating `kbsecret` with `gem`, if you've installed it from RubyGems, and let me know if the error persists.

**Comment by Asternitix** [comment]
should I undo the changes I made to config.rb?

**Comment by Asternitix** [comment]
should it say label.to_sys instead of label.to_s?

**Comment by woodruffw** [comment]
> should I undo the changes I made to config.rb?

Updating should do that for you.

> should it say label.to_sys instead of label.to_s?

Nope! `to_s` is Ruby for "convert this object to a String".

**Comment by Asternitix** [comment]
it was saying label.to_sys before I changed it.

**Comment by woodruffw** [comment]
> it was saying label.to_sys before I changed it.

You mean `label.to_sym`? I can't find `label.to_sys` in my copy of `config.rb`.

**Comment by Asternitix** [comment]
that's the one.

**Comment by Asternitix** [comment]
was that a bug?

**Comment by woodruffw** [comment]
> that's the one.

Yeah, that's fine then. `to_sym` just converts an object into a Symbol.

> was that a bug?

Nope.

**Comment by Asternitix** [comment]
it was spitting out error messages when it had that in the file.

**Comment by woodruffw** [comment]
> it was spitting out error messages when it had that in the file.

Do you have the exact error message? `to_sym` and `to_s` are normal calls, and I haven't experienced any errors in this part of the code.

**Comment by Asternitix** [comment]
How do I update kbsecret using gem?

**Comment by woodruffw** [comment]
> How do I update kbsecret using gem?

Try `gem update kbsecret`

**Comment by Asternitix** [comment]
Yeah, I'll send them to you before I update kbsecret.

**Comment by Asternitix** [comment]
it happens in debian stretch

**Comment by Asternitix** [comment]
I'll have access to the computer in question tomorrow. goodnight.

**Comment by Asternitix** [comment]
the errors from to_sym aren't happening anymore.

**Comment by Asternitix** [comment]
I updated kbsecret, the blank session is still there.

**Comment by woodruffw** [comment]
> I updated kbsecret, the blank session is still there.

Could you clarify? What's the output of `kbsecret sessions`?

**Comment by Asternitix** [comment]
/var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/config.rb:143:in `block (2 levels) in <class:Config>': Unknown session: '' (KBSecret::Exceptions::SessionUnknownError)
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/cli/kbsecret-sessions:20:in `block in <main>'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/cli/kbsecret-sessions:19:in `each'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/cli/kbsecret-sessions:19:in `<main>'

**Comment by woodruffw** [comment]
Okay. That suggests that there's a session named `""` (the empty string) in your `config.yml`.

Could you paste the contents of `~/.config/kbsecret/config.yml` here? Note that that file is different from `config.rb`.

**Comment by Asternitix** [comment]
```yaml
:mount: "/keybase"
:sessions:
  '':
    :users:
    - asternitix
    :root: 
  :default:
    :users:
    - asternitix
    :root: default
:generators:
  :default:
    :format: hex
    :length: 16
```

**Comment by Asternitix** [comment]
oops.
/usr/lib/ruby/2.3.0/psych.rb:379:in `parse': (/home/asternitx/.config/kbsecret/config.yml): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
        from /usr/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
        from /usr/lib/ruby/2.3.0/psych.rb:327:in `parse'
        from /usr/lib/ruby/2.3.0/psych.rb:254:in `load'
        from /usr/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
        from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
        from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/config.rb:168:in `<class:Config>'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/config.rb:10:in `<module:KBSecret>'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret/config.rb:8:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret.rb:7:in `require_relative'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/lib/kbsecret.rb:7:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/kbsecret-0.9.3/bin/kbsecret:4:in `<top (required)>'
        from /usr/local/bin/kbsecret:22:in `load'
        from /usr/local/bin/kbsecret:22:in `<main>'

**Comment by Asternitix** [comment]
I removed the '': and that happened when I ran kbsecret sessions

**Comment by woodruffw** [comment]
> I removed the '': and that happened when I ran kbsecret sessions

Remove the 3 lines below it as well. Your config should look like this:

```yaml
:mount: "/keybase"
:sessions:
  :default:
    :users:
    - asternitix
    :root: default
:generators:
  :default:
    :format: hex
    :length: 16
```

**Comment by Asternitix** [comment]
that fixed it. thank you so much!

**Comment by Asternitix** [comment]
how do I fix
Fatal: No implicit conversion of nil into string.

**Comment by woodruffw** [comment]
What did you run that gave you that error?

**Comment by Asternitix** [comment]
kbsecret sessions after new-session -l chicken -u asternitix

**Comment by Asternitix** [comment]
should I change to_s to to_sym?

**Comment by Asternitix** [comment]
that's weird it's to_sym.

**Comment by woodruffw** [comment]
> kbsecret sessions after new-session -l chicken -u asternitix

You're missing a flag. The invocation should be `kbsecret new-session -l chicken -r whatever -u asternitix`, where "whatever" is the directory you want KBSecret to create for the session.

**Comment by Asternitix** [comment]
oh.

**Comment by Asternitix** [comment]
fixed it.

**Comment by woodruffw** [comment]
> fixed it.

Cool. I've added a guard in https://github.com/kbsecret/kbsecret/commit/602e37edf2351fc8ecfa389871d471572638b38b to make that error more descriptive.
