### ISSUE TITLE
kbsecret interferes with keybase's usage of kbfs

### ISSUE THREAD

**Issue by Asternitix** [kbsecret/kbsecret.github.io#3]
Username:      asternitix
Logged in:     yes

Session:       no session
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    not cached
    secret:    stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached

KBFS:
    status:    not running
    version:   1.0.2-20171010160025+f71e33c2
    log:       /home/asternitx/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.34-20171010160025+8543c4734
    log:       /home/asternitx/.cache/keybase/keybase.service.log

Updater:
    log:       /home/asternitx/.cache/keybase/keybase.updater.log

Platform Information:
    OS:        linux
    OS vers:   Linux 3.8.11 x86_64-Debian GNU/Linux 9.2 (stretch)
    Runtime:   go1.9
    Arch:      amd64

Client:
    version:   1.0.34-20171010160025+8543c4734

Desktop app:
    status:    not running
    version:   
    log:       /home/asternitx/.cache/keybase/Keybase.app.log

Config path:   /home/asternitx/.config/keybase/config.json
Default user:  asternitix
Other users:   

command-line client:
    keybase status [pid: 14189, version: 1.0.34-20171010160025+8543c4734]

kbsecret keeps kbfs from running

▶ ERROR GetConversationForCLILocal error: error unboxing chat message: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with `run_keybase` command.

▶ ERROR GetConversationForCLILocal error: error unboxing chat message: Keybase services aren't running - KBFS client not found. On Linux you need to start them after an update with `run_keybase` command.

**Comment by woodruffw** [comment]
Can you reopen this issue on the [main issue tracker](https://github.com/kbsecret/kbsecret/issues)? This issue tracker is primarily for the website.
