### ISSUE TITLE
Error running `kbsecret session new api-keys --team megacorp.devs`

### ISSUE THREAD

**Issue by reedlaw** [kbsecret/kbsecret.github.io#4]
I was trying to follow the guide but I got this:

```
/home/reed/.gem/ruby/2.4.0/gems/kbsecret-0.9.5/lib/kbsecret/cli/kbsecret-session:14:in `new_session': undefined method `list_memberships' for Keybase::Local::Team:Module (NoMethodError)    
Did you mean?  list_team_memberships
        from /home/reed/.gem/ruby/2.4.0/gems/kbsecret-0.9.5/lib/kbsecret/cli/kbsecret-session:89:in `<main>'  
```

**Comment by woodruffw** [comment]
Looks like I accidentally introduced a dependency mismatch all the way over here: https://github.com/kbsecret/keybase-unofficial/commit/24e6d151264e69ea704fb5b181ec7d62fa07ccaa - KBSecret `0.9.5` isn't supposed to use that new version.

I'll have 0.9.6 released in a bit, and everything should work from there. Sorry for the inconvenience!

**Comment by woodruffw** [comment]
Just released 0.9.6, which should fix your problem when you update to it.

**Comment by reedlaw** [comment]
That was fast, thank you!

**Comment by woodruffw** [comment]
No problem! Let me know if you have any other problems.
